name: CI with Checkstyle and SonarCloud

on:
  push:
    branches:
      - 'huda/**'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Build, Lint, and Analyze
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup JDK 21
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      # Beri izin execute pada gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Checkstyle
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      # Build and Testing
      - name: Build and Test with Gradle
        run: ./gradlew build

      # Analisis SonarCloud
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar -Dsonar.qualitygate.wait=true --info